### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by rlpowell** [zerowidth/camper_van#13]
No idea what happened here, but:

2012-05-31 15:42:20 13200  INFO CamperVan : performing request to https://engineyard.campfirenow.com.campfirenow.com/users/789439.json
2012-05-31 15:42:21 13200  WARN CamperVan : WARNING: Tried to set starred= "false" on a Firering::Message instance but it didn't respond. Probably the API got updated, please report this! (https://github.com/EmmanuelOga/firering/issues)
2012-05-31 15:42:21 13200  INFO CamperVan : closed connection from 209.251.180.162
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200  INFO CamperVan : closed connection from 76.180.129.249
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200  INFO CamperVan : closed connection from 72.45.208.163
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
2012-05-31 15:42:21 13200 ERROR CamperVan : http error . Trying again in 2 seconds...
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/camper_van-0.0.3/lib/camper_van/channel.rb:267:in `block in map_message_to_irc': unexpected return (LocalJumpError)
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/camper_van-0.0.3/lib/camper_van/channel.rb:389:in`block in user_for_message'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/firering-1.1.1/lib/firering/instantiator.rb:28:in `call'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/firering-1.1.1/lib/firering/instantiator.rb:28:in`instantiate'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/firering-1.1.1/lib/firering/requests.rb:15:in `block in user'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/firering-1.1.1/lib/firering/connection.rb:68:in`call'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/firering-1.1.1/lib/firering/connection.rb:68:in `block in http'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/em/deferrable.rb:134:in`call'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/em/deferrable.rb:134:in `set_deferred_status'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/em/deferrable.rb:173:in`succeed'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/em-http-request-0.3.0/lib/em-http/client.rb:307:in `unbind'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/eventmachine.rb:1417:in`event_callback'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/camper_van-0.0.3/lib/camper_van/server.rb:21:in `run'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/camper_van-0.0.3/bin/camper_van:64:in`<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/camper_van:19:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/camper_van:19:in`<main>'

**Comment by zerowidth** [comment]
This is fixed in the 0.0.4 release.
