### ISSUE TITLE
RuntimeError when starting camper_van

### ISSUE THREAD

**Issue by linduxed** [zerowidth/camper_van#32]
When I try to run `camper_van` with no arguments I get this:

```
2013-05-07 03:27:40 23709  INFO CamperVan : starting server on 127.0.0.1:6667
/home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server': no acceptor (RuntimeError)
        from /home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_server'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/camper_van-0.0.9/lib/camper_van/server.rb:24:in `block in run'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/camper_van-0.0.9/lib/camper_van/server.rb:21:in `run'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/lib/ruby/gems/1.9.1/gems/camper_van-0.0.9/bin/camper_van:64:in `<top (required)>'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/bin/camper_van:23:in `load'
        from /home/linduxed/.rbenv/versions/1.9.2-p320/bin/camper_van:23:in `<main>'
```

Could it be a setup issue of some kind?

**Comment by zerowidth** [comment]
Might be an eventmachine error. I'd also suggest updating to the latest ruby 1.9.3 version.

I've had several reports of EM-related issues with the old versions used by camper_van in #29, perhaps that might help also.

**Comment by linduxed** [comment]
After noticing that [flamethrower](https://github.com/blakesmith/flamethrower) did the same thing, I noticed that I had bitlbee running, which also uses port 6667. Passing the `-p` flag with a different port made it work, so I assume that this is the root of the issue. Silly error on my end.

**Comment by zerowidth** [comment]
Ok cool :) Sucks that the error message isn't more obvious!
