### ISSUE TITLE
First time I speak camper_van crashes

### ISSUE THREAD

**Issue by devn** [zerowidth/camper_van#6]
I can reliably reproduce camper_van crashing by connecting to campfire, joining the channel, and saying something. I then restart camper_van and connect again and it works, but I get 2 messages at once.

```
2012-02-24 09:39:32 29407  INFO CamperVan : got connection from 127.0.0.1
2012-02-24 09:39:32 29407  INFO CamperVan : performing request to https://example.campfirenow.com/users/me.json
2012-02-24 09:39:33 29407  INFO CamperVan : performing request to https://example.campfirenow.com/users/me.json
2012-02-24 09:39:38 29407  INFO CamperVan : performing request to https://example.campfirenow.com/rooms.json
2012-02-24 09:39:39 29407  INFO CamperVan : performing request to https://example.campfirenow.com/room/423619.json
2012-02-24 09:39:39 29407  INFO CamperVan : performing request to https://example.campfirenow.com/room/423619/join.json
2012-02-24 09:39:40 29407  INFO CamperVan : performing streaming request to https://streaming.campfirenow.com/room/423619/live.json
2012-02-24 09:39:46 29407  INFO CamperVan : performing request to https://example.campfirenow.com/room/423619/speak.json
2012-02-24 09:39:49 29407  WARN CamperVan : WARNING: Tried to set starred= "false" on a Firering::Message instance but it didn't respond. Probably the API got updated, please report this! (https://github.com/EmmanuelOga/firering/issues)
2012-02-24 09:39:49 29407  INFO CamperVan : performing request to https://example.campfirenow.com/users/960484.json
2012-02-24 09:39:50 29407  INFO CamperVan : closed connection from 127.0.0.1
2012-02-24 09:39:50 29407 ERROR CamperVan : http error . Trying again in 2 seconds...
/Users/myusername/src/camper_van/lib/camper_van/channel.rb:266:in `block in map_message_to_irc': unexpected return (LocalJumpError)
        from /Users/myusername/src/camper_van/lib/camper_van/channel.rb:390:in `block in user_for_message'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/firering-1.1.1/lib/firering/instantiator.rb:28:in `call'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/firering-1.1.1/lib/firering/instantiator.rb:28:in `instantiate'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/firering-1.1.1/lib/firering/requests.rb:15:in `block in user'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/firering-1.1.1/lib/firering/connection.rb:68:in `call'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/firering-1.1.1/lib/firering/connection.rb:68:in `block in http'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/eventmachine-0.12.10/lib/em/deferrable.rb:134:in `call'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/eventmachine-0.12.10/lib/em/deferrable.rb:134:in `set_deferred_status'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/eventmachine-0.12.10/lib/em/deferrable.rb:173:in `succeed'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/em-http-request-0.3.0/lib/em-http/client.rb:307:in `unbind'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/eventmachine-0.12.10/lib/eventmachine.rb:1417:in `event_callback'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
        from /Users/myusername/src/camper_van/lib/camper_van/server.rb:21:in `run'
        from /Users/myusername/src/camper_van/bin/camper_van:57:in `<top (required)>'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/bin/camper_van:19:in `load'
        from /Users/myusername/.rvm/gems/ruby-1.9.3-p0@camper_van/bin/camper_van:19:in `<main>'
```

**Comment by zerowidth** [comment]
I've updated the gem dependencies to the latest version of firering, can you try with the git version?
